steps:
- name: 'gcr.io/cloud-builders/python-cloudbuild'
  entrypoint: '/bin/bash'
  args: ['-c','virtualenv /workspace/venv']
- name: 'gcr.io/cloud-builders/python-cloudbuild'
  entrypoint: 'venv/bin/pip'
  args: ['install', '-V', '-r', 'requirements.txt']  
- name: 'gcr.io/cloud-builders/python-cloudbuild'
  entrypoint: 'venv/bin/python'
  args: ['-m', 'pytest', '-v']
- name: 'gcr.io/cloud-builders/python-cloudbuild'
  entrypoint: 'venv/bin/pylint'
  args: ['my_module/']