steps:
  - name: python:3.7
    id: INSTALL
    entrypoint: python3
    args: ['-m', 'pip', 'install', '-r', 'requirements.txt']
  - name: python:3.7
    entrypoint: python3
    id: RUN-UNIT-TESTS
    args: ['-m', 'pytest', '-v']